#!/bin/bash

# Edit this to installation directory
BASEDIR=~/code/tenforce-report-typesetting
 
NAME=$1
FORMAT=$2

if [ ! -f $NAME.md ]
then
  echo "Error: $NAME.md does not exist or not specified."
  echo "Usage: typeset NAME [FORMAT]"
  echo "Optional [FORMAT] parameter can be set to 'odt' or 'docx', otherwise outputs .tex and .pdf files."
  exit 1
fi

TMP=`mktemp -d`

if [[ $FORMAT = "odt" ]]
then
  ODTTEMPLATE=`[ -f template.odt ] && echo "template.odt" || echo $BASEDIR/template.odt`
  echo "Typesetting: $NAME.md => $NAME.odt"
  echo "Using template: $ODTTEMPLATE"
  pandoc --template $ODTTEMPLATE -f markdown+grid_tables -o $TMP/$NAME.odt $NAME.md
  mv $TMP/$NAME.odt .
elif [[ $FORMAT = "docx" ]]
then
  WORDTEMPLATE=`[ -f template.docx ] && echo "template.docx" || echo $BASEDIR/template.docx`
  echo "Typesetting: $NAME.md => $NAME.docx"
  echo "Using template: $WORDTEMPLATE"
  pandoc --template $WORDTEMPLATE -f markdown+grid_tables  -o $TMP/$NAME.docx $NAME.md
  mv $TMP/$NAME.docx .
else
  LATEXTEMPLATE=`[ -f template.tex ] && echo "template.tex" || echo $BASEDIR/template.tex`
  echo "Typesetting: $NAME.md => $NAME.pdf + .tex"
  echo "Using template: $LATEXTEMPLATE"

  echo "`sed s#\<BASEDIR\>#$BASEDIR#g $BASEDIR/template.tex`" >> $TMP/template.tex

  pandoc --template $TMP/template.tex -f markdown+grid_tables -t latex -o $TMP/$NAME.tex $NAME.md
  pandoc --template $TMP/template.tex -f markdown+grid_tables -t latex -o $TMP/$NAME.pdf $NAME.md

  mv $TMP/$NAME.tex .
  mv $TMP/$NAME.pdf .
fi

rm -rf $TMP
